[2022-01-31 19:44:09,002] {taskinstance.py:1032} INFO - Dependencies all met for <TaskInstance: data_ingestion_fhv_data.local_to_gcs_task scheduled__2019-01-01T00:00:00+00:00 [queued]>
[2022-01-31 19:44:09,341] {taskinstance.py:1032} INFO - Dependencies all met for <TaskInstance: data_ingestion_fhv_data.local_to_gcs_task scheduled__2019-01-01T00:00:00+00:00 [queued]>
[2022-01-31 19:44:09,346] {taskinstance.py:1238} INFO - 
--------------------------------------------------------------------------------
[2022-01-31 19:44:09,352] {taskinstance.py:1239} INFO - Starting attempt 1 of 2
[2022-01-31 19:44:09,358] {taskinstance.py:1240} INFO - 
--------------------------------------------------------------------------------
[2022-01-31 19:44:09,580] {taskinstance.py:1259} INFO - Executing <Task(PythonOperator): local_to_gcs_task> on 2019-01-01 00:00:00+00:00
[2022-01-31 19:44:09,618] {standard_task_runner.py:52} INFO - Started process 4514 to run task
[2022-01-31 19:44:09,675] {standard_task_runner.py:76} INFO - Running: ['***', 'tasks', 'run', 'data_ingestion_fhv_data', 'local_to_gcs_task', 'scheduled__2019-01-01T00:00:00+00:00', '--job-id', '350', '--raw', '--subdir', 'DAGS_FOLDER/data_ingestion_fhv_data.py', '--cfg-path', '/tmp/tmpb81n4anr', '--error-file', '/tmp/tmp7_q4ff1l']
[2022-01-31 19:44:09,690] {standard_task_runner.py:77} INFO - Job 350: Subtask local_to_gcs_task
[2022-01-31 19:44:10,270] {logging_mixin.py:109} INFO - Running <TaskInstance: data_ingestion_fhv_data.local_to_gcs_task scheduled__2019-01-01T00:00:00+00:00 [running]> on host d8f3de29471d
[2022-01-31 19:44:10,859] {warnings.py:110} WARNING - /home/***/.local/lib/python3.7/site-packages/***/utils/context.py:152: AirflowContextDeprecationWarning: Accessing 'execution_date' from the template is deprecated and will be removed in a future version. Please use 'data_interval_start' or 'logical_date' instead.
  warnings.warn(_create_deprecation_warning(key, self._deprecation_replacements[key]))

[2022-01-31 19:44:11,164] {taskinstance.py:1426} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=data_ingestion_fhv_data
AIRFLOW_CTX_TASK_ID=local_to_gcs_task
AIRFLOW_CTX_EXECUTION_DATE=2019-01-01T00:00:00+00:00
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2019-01-01T00:00:00+00:00
[2022-01-31 19:44:25,799] {taskinstance.py:1026} INFO - Dependencies not met for <TaskInstance: data_ingestion_fhv_data.local_to_gcs_task scheduled__2019-01-01T00:00:00+00:00 [running]>, dependency 'Task Instance Not Running' FAILED: Task is in the running state
[2022-01-31 19:44:25,810] {taskinstance.py:1026} INFO - Dependencies not met for <TaskInstance: data_ingestion_fhv_data.local_to_gcs_task scheduled__2019-01-01T00:00:00+00:00 [running]>, dependency 'Task Instance State' FAILED: Task is in the 'running' state.
[2022-01-31 19:44:25,921] {local_task_job.py:99} INFO - Task is not able to be run
[2022-01-31 19:45:13,065] {python.py:175} INFO - Done. Returned value was: None
[2022-01-31 19:45:13,138] {taskinstance.py:1277} INFO - Marking task as SUCCESS. dag_id=data_ingestion_fhv_data, task_id=local_to_gcs_task, execution_date=20190101T000000, start_date=20220131T194409, end_date=20220131T194513
[2022-01-31 19:45:13,253] {local_task_job.py:154} INFO - Task exited with return code 0
[2022-01-31 19:45:13,371] {local_task_job.py:264} INFO - 1 downstream tasks scheduled from follow-on schedule check
